lucidrains/audiolm-pytorch

- audiolm_pytorch/audiolm_pytorch.py
I think it is error at class of STFTDiscriminator,  the related content of the paper  is as follows:
```
The STFT-based discriminator is illustrated in Figure 4
and operates on a single scale, computing the STFT with a
window length of W = 1024 samples and a hop length of
H = 256 samples
```
Do you agree with me?
> fixed a errors of STFTDiscriminator

- audiolm_pytorch/data.py
Currently we always take the beginning of the audio file up to `max_length`. This prevents us from making full use of the data (especially when dealing with lots of long audio files). This change selects random parts of the audio file rather than always cropping from the start. It also pads audio files shorter than `max_length`.  Feel free to re-work this but you get the idea.
> Random audio selection and padding as required

- audiolm_pytorch/data.py
This is more natural when listening to generated samples while training sound stream (prevents long silences when audio source < data_max_length).
Please confirm this doesn't have negative consequences on expectations elsewhere...
> Pad right side of audio vs. left

- audiolm_pytorch/trainer.py
Without this, "sample.flac" keeps getting overwritten, and it's nice to have a history of how the training is progressing.
> Make the training sample output filename unique

- audiolm_pytorch/trainer.py
This supports visualization tools e.g. tensorboard.  It required initializing the accelerator trackers.  If that's done before the "do you want to clear' step it can lead to weird edge cases.
> Add Accelerate init_tracker and log losses

- audiolm_pytorch/data.py
It is annoying when training on large data sets for one non-mono file to cause an exception (einops.EinopsError: Shape mismatch, 2 != 1) and the whole training pipeline to crash.  Weeding out such files can take some time.  This will avoid such crashes and handle them gracefully...
> Convert stereo/multi-channel audio to mono

- audiolm_pytorch/audiolm_pytorch.py
generate() in CoarseTransformerWrapper and FineTransformerWrapper only uses initial tokens. Pass in sampled tokens instead
> fix generate

- audiolm_pytorch/audiolm_pytorch.py
- batch unique consecutive semantic token ids in generate() function of CoarseTransformerWrapper
- get semantic tokens with get_embeds() in CoarseTransformer to avoid issues with padding tokens
> batch unique consecutive in CoarseTransformer

- audiolm_pytorch/soundstream.py
Adds a bit too much noise when printing the losses :-)
> Remove print statement from debugging

- audiolm_pytorch/soundstream.py
- audiolm_pytorch/trainer.py
Some `SoundStreamTrainer` improvements:
1. Log all losses through the `Accelerator` to get a better understanding of what is going on during the training;
2. Synchronize gradient penalties for `STFT` and `MultiScaleDiscriminators`;
3. Allow turning off the EMA model with `use_ema` (as done in your other repos);
4. Fix saving of EMA model samples during training.
> SoundStreamTrainer tweaks

- audiolm_pytorch/audiolm_pytorch.py
Only the wrappers seem to use this, e.g. [SemanticTransformerWrapper](https://github.com/lucidrains/audiolm-pytorch/blob/main/audiolm_pytorch/audiolm_pytorch.py#L945)
> remove unused pad_id

- audiolm_pytorch/soundstream.py
As per discussion at https://github.com/lucidrains/audiolm-pytorch/issues/80, the default `strides` for the `SoundStream` class is set at (2, 4, 5, 8) = 320, which is the strides value found in the AudioLM paper for a 16kHz sampling rate. However, the SoundStream class' default sampling rate (`target_sample_hz`) is 24kHz, for which the MusicLM paper specifies a strides value of 480 (e.g. (3, 4, 5, 8) ). If I haven't missed/or misunderstood something, IMO it'd make sense to have the default `strides` and `target_sample_hz` values in line with one another, hence I've made that change in this PR. Thanks to Afiyetolsun for confirming.
> Modify default SoundStream strides to 480 to match default 24kHz sampling rate

- audiolm_pytorch/data.py
- audiolm_pytorch/trainer.py
This is needed for multi-GPU use cases where certain actions need to be performed on the main process before the trainer is constructed.
Also minor tweak to accept more audio types in the data loader.
> Option to pass in Accelerator to SoundStreamTrainer

- audiolm_pytorch/encodec.py
- audiolm_pytorch/trainer.py
Minor bugs
- `functools`, `einops`, and `torch` import missing from `encodec.py`
- Coarse transformer trainer was saving its checkpoints with "fine" in the filename
> Minor patch, couple imports missing

- audiolm_pytorch/encodec.py
Found two bugs in encodec.py
- the concatenation of `encoded` should be last dimension instead of dim=1 (it's num_quantizers).
- if return_encoded is false, exception will be thrown at line `emb, = unpack(emb, ps, '* n c')`, since emb is None.
> Bug fix in encodec.py

- audiolm_pytorch/audiolm_pytorch.py
- audiolm_pytorch/trainer.py
Since we no longer want to instantiate multiple Trainer instances.
Also fixes a device-related bug in the process (see last commit): 
> This was covered up by previous usage where we'd instantiate trainers for each transformer (semantic/coarse/fine). Now that we have to be able to load transformers without their corresponding trainers, because we can only load one accelerator at a time, the code in trainer that checks wrapper device no longer applies and we get device mismatches. This commit fixes that
--
I tested this code and was able to get a small training run of a few hundred steps working so it works e2e!
> Separate transformer and trainer checkpoint load logic

- audiolm_pytorch/trainer.py
Bugfix addressing [#242](https://github.com/lucidrains/audiolm-pytorch/issues/242)
`valid_dataset` should set `self.valid_ds` to remain consistent with the code, otherwise an error is thrown that `self.valid_ds` doesn't exist.
> Bugfix - Fixing validation dataset variable on FineTransformerTrainer

- audiolm_pytorch/audiolm_pytorch.py
quick bugfix responding to [#246 ](https://github.com/lucidrains/audiolm-pytorch/issues/246)
changing `encodec` to `self.codec` 
With this change,  you can `set return_coarse_generated_wave=True` and return just the wave generated by the coarse transformer.
> bugfix - swap codec variable for course wrapper

- audiolm_pytorch/trainer.py
In the `__init__`s of `SemanticTransformerTrainer`, `CoarseTransformerTrainer` and `FineTransformerTrainer`, the attribute `self.use_wandb_tracking` was only set when the parameter `use_wandb_tracking` was `True`. This caused the Trainers to throw an `AttributeError` upon training when not using WandB.
This is now fixed.
> `use_wandb_tracking` was not stored in most Trainers when it is `False`

- audiolm_pytorch/audiolm_pytorch.py
The output of the Attention should be assigned back to x. The `attn_out` is not used anywhere. So this is a bug in the code.
> fix wrong tensor assignment of the output of attention
